language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7-dev
    - pypy
    - pypy3
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
    - coverage run setup.py -q test -q
after_success:
    - coveralls
notifications:
    email: false
cache: pip
